import { useEffect, useState } from "react";
import { PageHeader, DataTable, Modal, Field, Input, Select, Button, StatusPill, useCRUD } from "./_shared";
import { api, fmtDate, fmtIDR, formatErr } from "@/lib/api";
import { toast } from "sonner";

export default function CRM() {
  const { rows: customers, save } = useCRUD("customers"); const { rows: activities, save: saveActivity, reload } = useCRUD("crm_activities"); const [selected,setSelected]=useState(null); const [form,setForm]=useState(null);
  const customerActivities=activities.filter(x=>x.customer_id===selected?.id);
  const addActivity=async()=>{if(await saveActivity({...form,customer_id:selected.id,status:"open"},form.id)){setForm(null);reload();}};
  return <div><PageHeader title="Light CRM" subtitle="Customer relationships & follow-ups" action={<Button onClick={()=>setSelected(customers[0])}>Open customer</Button>}/><div className="grid lg:grid-cols-[1fr_360px] gap-4"><DataTable rows={customers} columns={[{header:"Customer",cell:r=><button className="font-semibold text-left hover:underline" onClick={()=>setSelected(r)}>{r.name}</button>},{header:"Contact",cell:r=>r.phone||r.email||"-"},{header:"Segment",cell:r=><StatusPill status={r.customer_type||"new"}/>},{header:"Orders",cell:r=>r.total_orders||0},{header:"Lifetime value",cell:r=>fmtIDR(r.total_spending||0)},{header:"Last order",cell:r=>fmtDate(r.last_order)}]}/>{selected&&<div className="p-5 rounded-lg border border-border bg-card h-fit space-y-4"><div><div className="text-xs text-muted-foreground">Customer</div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm">{selected.email||"-"} · {selected.phone||"-"}</p></div><div className="grid grid-cols-2 gap-2 text-sm"><Summary label="Orders" value={selected.total_orders||0}/><Summary label="Value" value={fmtIDR(selected.total_spending||0)}/></div><div className="flex justify-between items-center"><b>Activities</b><Button variant="outline" onClick={()=>setForm({type:"note",subject:"",description:"",due_date:""})}>+ Activity</Button></div>{customerActivities.map(a=><div key={a.id} className="border-t pt-2 text-sm"><div className="font-semibold">{a.subject||a.type}</div><div>{a.description}</div><div className="text-xs text-muted-foreground">{fmtDate(a.due_date)} · {a.status}</div></div>)}</div>}</div>{form&&<Modal open onClose={()=>setForm(null)} title="Customer activity"><div className="space-y-3"><Field label="Type"><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="note">Note</option><option value="call">Call</option><option value="task">Task</option><option value="follow_up">Follow-up</option></Select></Field><Field label="Subject"><Input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></Field><Field label="Description"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Due date"><Input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Field><Button onClick={addActivity}>Save</Button></div></Modal>}</div>;
}
function Summary({label,value}) { return <div className="p-2 bg-stone-100 dark:bg-stone-900 rounded"><div className="text-xs text-muted-foreground">{label}</div><b>{value}</b></div>; }
