import { useEffect, useState } from "react";
import { PageHeader, DataTable, Modal, Field, Input, Select, Button, StatusPill, useCRUD } from "./_shared";
import { api, fmtIDR, fmtDate, formatErr } from "@/lib/api";
import { toast } from "sonner";

export default function FinanceSuite() {
  const [tab, setTab] = useState("ledger");
  const tabs = [["ledger", "Buku Besar & Jurnal"], ["invoices", "Faktur & Tagihan"], ["ap-ar", "Hutang & Piutang"], ["bank", "Rekonsiliasi Bank"], ["tax", "Pajak"], ["reports", "Laporan Dasar"]];
  return <div><PageHeader title="Finance Suite" subtitle="Accounting, receivables, payables & tax"/>
    <div className="flex gap-2 flex-wrap mb-4">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`px-4 py-2 rounded-md text-xs font-semibold uppercase tracking-widest ${tab===key?"bg-neutral-900 text-white":"bg-stone-100 dark:bg-stone-900"}`}>{label}</button>)}</div>
    {tab==="ledger" && <Ledger/>}{tab==="invoices" && <Invoices/>}{tab==="ap-ar" && <ApAr/>}{tab==="bank" && <BankReconciliation/>}{tab==="tax" && <Tax/>}{tab==="reports" && <BasicReports/>}
  </div>;
}

function Ledger() {
  const { rows: accounts } = useCRUD("accounts"); const [rows,setRows]=useState([]); const [modal,setModal]=useState(null);
  const reload=()=>api.get("/finance/journal_entries").then(r=>setRows(r.data));
  useEffect(()=>{reload();},[]);
  const save=async()=>{try{await api.post("/finance/journal_entries",{...modal,lines:modal.lines.map(x=>({...x,debit:Number(x.debit||0),credit:Number(x.credit||0)}))});toast.success("Jurnal tersimpan");setModal(null);reload();}catch(e){toast.error(formatErr(e.response?.data?.detail));}};
  return <div><div className="flex justify-end mb-3"><Button onClick={()=>setModal({description:"",reference:"",lines:[{account_id:"",debit:0,credit:0},{account_id:"",debit:0,credit:0}]})}>+ Jurnal Umum</Button></div><DataTable rows={rows} columns={[{header:"Tanggal",cell:r=>fmtDate(r.date)},{header:"Referensi",cell:r=>r.reference||"-"},{header:"Deskripsi",cell:r=>r.description},{header:"Total",cell:r=><b>{fmtIDR(r.total)}</b>}]}/>{modal&&<Modal open onClose={()=>setModal(null)} title="Jurnal Umum"><div className="space-y-3"><Field label="Description"><Input value={modal.description} onChange={e=>setModal({...modal,description:e.target.value})}/></Field><Field label="Reference"><Input value={modal.reference} onChange={e=>setModal({...modal,reference:e.target.value})}/></Field>{modal.lines.map((line,i)=><div className="grid grid-cols-[1fr_120px_120px] gap-2" key={i}><Select value={line.account_id} onChange={e=>{const lines=[...modal.lines];lines[i]={...line,account_id:e.target.value};setModal({...modal,lines});}}><option value="">Account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select><Input type="number" placeholder="Debit" value={line.debit} onChange={e=>{const lines=[...modal.lines];lines[i]={...line,debit:e.target.value};setModal({...modal,lines});}}/><Input type="number" placeholder="Credit" value={line.credit} onChange={e=>{const lines=[...modal.lines];lines[i]={...line,credit:e.target.value};setModal({...modal,lines});}}/></div>)}<Button variant="outline" onClick={()=>setModal({...modal,lines:[...modal.lines,{account_id:"",debit:0,credit:0}]})}>+ Line</Button><Button onClick={save}>Simpan Jurnal</Button></div></Modal>}</div>;
}

function Invoices() {
  const { rows: invoices, save, remove, reload: reloadInvoices } = useCRUD("invoices"); const { rows: bills, reload: reloadBills } = useCRUD("bills"); const { rows: accounts } = useCRUD("accounts"); const [kind,setKind]=useState("invoice"); const [form,setForm]=useState(null); const [payment,setPayment]=useState(null);
  const collection=kind==="invoice"?invoices:bills; const submit=async()=>{if(await save({...form,amount:Number(form.amount),paid_amount:0,status:"unpaid"},form.id))setForm(null);};
  const pay=async()=>{try{await api.post(`/finance/${payment.kind==="invoice"?"invoices":"bills"}/${payment.id}/payment`,{amount:Number(payment.amount),account_id:payment.account_id});toast.success("Payment recorded");setPayment(null);reloadInvoices();reloadBills();}catch(e){toast.error(formatErr(e.response?.data?.detail));}};
  return <div><div className="flex justify-between mb-3"><div className="flex gap-2"><Button variant={kind==="invoice"?"primary":"outline"} onClick={()=>setKind("invoice")}>Sales Invoice</Button><Button variant={kind==="bill"?"primary":"outline"} onClick={()=>setKind("bill")}>Vendor Bill</Button></div><Button onClick={()=>setForm({number:"",party_name:"",amount:0,due_date:"",description:""})}>+ {kind==="invoice"?"Invoice":"Bill"}</Button></div><DataTable rows={collection} columns={[{header:"Number",cell:r=>r.number},{header:"Party",cell:r=>r.party_name},{header:"Due",cell:r=>fmtDate(r.due_date)},{header:"Amount",cell:r=>fmtIDR(r.amount)},{header:"Paid",cell:r=>fmtIDR(r.paid_amount)},{header:"Status",cell:r=><StatusPill status={r.status||"unpaid"}/>},{header:"Action",cell:r=><div className="flex gap-2"><button className="text-blue-600" disabled={Number(r.paid_amount||0)>=Number(r.amount||0)} onClick={()=>setPayment({id:r.id,kind,amount:Number(r.amount||0)-Number(r.paid_amount||0),account_id:accounts.find(a=>a.is_default)?.id||accounts[0]?.id||""})}>Pay</button><button className="text-rose-600" onClick={()=>remove(r.id)}>Archive</button></div>}]}/>{form&&<Modal open onClose={()=>setForm(null)} title={kind==="invoice"?"Sales Invoice":"Vendor Bill"}><div className="grid grid-cols-2 gap-3"><Field label="Number"><Input value={form.number} onChange={e=>setForm({...form,number:e.target.value})}/></Field><Field label="Party"><Input value={form.party_name} onChange={e=>setForm({...form,party_name:e.target.value})}/></Field><Field label="Amount"><Input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Due date"><Input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Field><Field label="Description"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div><Button onClick={submit}>Simpan</Button></Modal>}{payment&&<Modal open onClose={()=>setPayment(null)} title={payment.kind==="invoice"?"Receive invoice payment":"Pay vendor bill"}><Field label="Amount"><Input type="number" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></Field><Field label="Account"><Select value={payment.account_id} onChange={e=>setPayment({...payment,account_id:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></Field><Button onClick={pay}>Record payment</Button></Modal>}</div>;
}

function ApAr() { const [data,setData]=useState({receivables:[],payables:[]}); useEffect(()=>{api.get("/finance/ap-ar").then(r=>setData(r.data));},[]); return <div className="grid md:grid-cols-2 gap-4"><Summary title="Piutang (AR)" value={data.receivables_total}/><Summary title="Hutang (AP)" value={data.payables_total}/><DataTable rows={data.receivables} columns={[{header:"Invoice",cell:r=>r.number},{header:"Customer",cell:r=>r.party_name},{header:"Outstanding",cell:r=>fmtIDR(Number(r.amount)-Number(r.paid_amount||0))}]}/><DataTable rows={data.payables} columns={[{header:"Bill",cell:r=>r.number},{header:"Supplier",cell:r=>r.party_name},{header:"Outstanding",cell:r=>fmtIDR(Number(r.amount)-Number(r.paid_amount||0))}]}/></div>; }
function Summary({title,value}) { return <div className="p-5 rounded-lg border border-border bg-card"><div className="text-xs text-muted-foreground">{title}</div><div className="text-2xl font-bold">{fmtIDR(value)}</div></div>; }
function BankReconciliation() { const {rows}=useCRUD("accounts"); const [items,setItems]=useState([]); useEffect(()=>{api.get("/finance/reconciliations").then(r=>setItems(r.data));},[]); return <div className="space-y-4"><DataTable rows={rows} columns={[{header:"Account",cell:r=>r.name},{header:"System balance",cell:r=>fmtIDR(r.balance)},{header:"Action",cell:r=><Reconcile account={r} onDone={()=>api.get("/finance/reconciliations").then(x=>setItems(x.data))}/>}]}/><DataTable rows={items} columns={[{header:"Date",cell:r=>fmtDate(r.created_at)},{header:"Account",cell:r=>r.account_id},{header:"Difference",cell:r=>fmtIDR(r.difference)},{header:"Notes",cell:r=>r.notes||"-"}]}/></div>; }
function Reconcile({account,onDone}) { const [open,setOpen]=useState(false); const [actual,setActual]=useState(account.balance||0); const submit=async()=>{try{await api.post("/finance/reconcile",{account_id:account.id,actual_balance:Number(actual),notes:"Bank reconciliation"});toast.success("Reconciliation saved");setOpen(false);onDone();}catch(e){toast.error(formatErr(e.response?.data?.detail));}}; return <><button className="text-blue-600" onClick={()=>setOpen(true)}>Reconcile</button>{open&&<Modal open onClose={()=>setOpen(false)} title={`Reconcile ${account.name}`}><Field label="Actual balance"><Input type="number" value={actual} onChange={e=>setActual(e.target.value)}/></Field><Button onClick={submit}>Save</Button></Modal>}</>; }
function Tax() { const [data,setData]=useState(null); const load=()=>api.get("/finance/tax-summary").then(r=>setData(r.data)); return <div className="space-y-4"><Button onClick={load}>Calculate tax summary</Button>{data&&<div className="grid md:grid-cols-3 gap-4"><Summary title="Output tax" value={data.output_tax}/><Summary title="Input tax" value={data.input_tax}/><Summary title="Net tax payable" value={data.net_tax}/></div>}</div>; }
function BasicReports() { const [data,setData]=useState(null); return <div className="space-y-4"><Button onClick={()=>api.get("/reports/profit_loss").then(r=>setData(r.data))}>Generate reports</Button>{data&&<div className="grid md:grid-cols-3 gap-4">{[["Revenue",data.revenue],["Gross profit",data.gross_profit],["Net profit",data.net_profit]].map(([x,v])=><Summary key={x} title={x} value={v}/>)}</div>}</div>; }
